# Task 2: Spam SMS Detection using Machine Learning

##CODSOFT Machine Learning Internship

This project classifies SMS messages as Spam or Ham using NLP techniques (TF-IDF) and Machine Learning model (SVM).

In [1]:
!pip install pandas numpy scikit-learn

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

## Step 1: Import required libraries

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import re

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score, classification_report
print("Libraries imported successfully!")

Libraries imported successfully!

## Step 2: Upload dataset (spam.csv)

In [10]:
from google.colab import files
uploaded = files.upload()

Saving archive (1).zip to archive (1).zip

## Step 3: Unzip the file

In [11]:
import zipfile

with zipfile.ZipFile("archive (1).zip", "r") as zip_ref:
    zip_ref.extractall()

print("Dataset extracted successfully!")

Dataset extracted successfully!

In [10]:
import os
os.listdir()

['.config', 'archive (1) (1).zip', 'archive (1).zip', 'sample_data']

##Step 4: Check extracted files

In [12]:
import zipfile

with zipfile.ZipFile("archive (1).zip", "r") as zip_ref:
    print(zip_ref.namelist())

['spam.csv']

In [13]:
import zipfile

with zipfile.ZipFile("archive (1).zip", "r") as zip_ref:
    zip_ref.extractall()

print("Dataset extracted successfully!")

Dataset extracted successfully!

In [14]:
import os

print(os.listdir())

['.config', 'spam.csv', 'archive (1).zip', 'sample_data']

##Step 5:Load the Dataset

In [42]:
df = pd.read_csv("spam.csv", encoding="latin-1")

In [43]:
df = df[['v1', 'v2']]

df.columns = ['label', 'message']

df.head()

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

##Step 6:Check Dataset

In [19]:
print("Rows and Coloumns:")
print(df.shape)

print("\nMissing Values:")
print(df.isnull().sum())

print("\nSpam vs Ham:")
print(df["label"].value_counts())

Rows and Coloumns:
(5572, 2)

Missing Values:
label      0
message    0
dtype: int64

Spam vs Ham:
label
ham     4825
spam     747
Name: count, dtype: int64

##Step 7:Convert labels into Numbers

In [44]:
df['label'] = df['label'].map({'ham': 0, 'spam': 1})
df.head()

   label                                            message
0      0  Go until jurong point, crazy.. Available only ...
1      0                      Ok lar... Joking wif u oni...
2      1  Free entry in 2 a wkly comp to win FA Cup fina...
3      0  U dun say so early hor... U c already then say...
4      0  Nah I don't think he goes to usf, he lives aro...

##Step8:Prepare/Separate Features and *Labels*

In [45]:
x = df['message']
y = df['label']

print(x.head())

print("\n")

print(y.head())

0    Go until jurong point, crazy.. Available only ...
1                        Ok lar... Joking wif u oni...
2    Free entry in 2 a wkly comp to win FA Cup fina...
3    U dun say so early hor... U c already then say...
4    Nah I don't think he goes to usf, he lives aro...
Name: message, dtype: object


0    0
1    0
2    1
3    0
4    0
Name: label, dtype: int64

##Step 9: Convert text into numbers (TF-IDF)

In [54]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(stop_words='english', max_features=5000 )
X = tfidf.fit_transform(x)
print(X.shape)

(5572, 5000)

##Step 9: Train-Test Split

In [58]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print(X_train.shape)
print(X_test.shape)

(4457, 5000)
(1115, 5000)

##Step10:Logical Regression

In [81]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

lr = LogisticRegression(max_iter=1000)
lr.fit(X_train, y_train)

lr_pred = lr.predict(X_test)

lr_accuracy = accuracy_score(y_test, lr_pred)
print("Logical Regression Accuracy:",lr_accuracy)
print("Predictions:", lr_pred[:10])

Logical Regression Accuracy: 0.9488789237668162
Predictions: [0 0 0 0 1 0 0 0 0 0]

##Step11:Naive Bayes

In [82]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

nb = MultinomialNB()
nb.fit(X_train, y_train)

nb_pred = nb.predict(X_test)

nb_accuracy = accuracy_score(y_test,nb_pred)

print("Naive Bayes Accuracy:", nb_accuracy)
print("Predictions:", nb_pred[:10])

Naive Bayes Accuracy: 0.9748878923766816
Predictions: [0 0 1 0 1 0 0 0 0 0]

##Step12:SVM (Support Vector Machine)

In [83]:
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score

svm = LinearSVC()
svm.fit(X_train, y_train)

svm_pred = svm.predict(X_test)

svm_accuracy = accuracy_score(y_test,svm_pred)

print("SVM Accuracy:", svm_accuracy)
print("Predictions:", svm_pred[:10])

SVM Accuracy: 0.9739910313901345
Predictions: [0 0 0 0 1 0 0 0 0 0]

##Step13:Compare Models

In [84]:
print("Logistic Regression:", lr_accuracy)
print("Naive Bayes:", nb_accuracy)
print("SVM:", svm_accuracy)

Logistic Regression: 0.9488789237668162
Naive Bayes: 0.9748878923766816
SVM: 0.9739910313901345

##Step14:Choose the Best Model

In [86]:
scores = {
    "Logistic Regression": lr_accuracy,
    "Naive Bayes": nb_accuracy,
    "SVM": svm_accuracy
}

best_model_name = max(scores, key=scores.get)

print("Model Scores:", scores)
print("Best Model:", best_model_name)

Model Scores: {'Logistic Regression': 0.9488789237668162, 'Naive Bayes': 0.9748878923766816, 'SVM': 0.9739910313901345}
Best Model: Naive Bayes

##Step15:Save the Model

In [75]:
import joblib

joblib.dump(best_model_name, "spam_model.pkl")
joblib.dump(tfidf, "tfidf_vectorizer.pkl")
print("Model saved successfully!")

Model saved successfully!

##Step16:Download

In [77]:
from google.colab import files

files.download("spam_model.pkl")
files.download("tfidf_vectorizer.pkl")

##Step17:Load

In [79]:
import joblib

model = joblib.load("spam_model.pkl")
tfidf = joblib.load("tfidf_vectorizer.pkl")

#Step 18:Tests
##Test_1

In [87]:
test1 = ["Free entry win cash prize"]

test1_vec = tfidf.transform(test1)

prediction = nb.predict(test1_vec)

if prediction[0] == 1:
    print("SPAM")
else:
    print("HAM")

SPAM

##Test_2

In [88]:
test2 = ["Hey are we meeting today?"]

test2_vec = tfidf.transform(test2)

prediction = nb.predict(test2_vec)

if prediction[0] == 1:
    print("SPAM")
else:
    print("HAM")

HAM

##Test_3

In [89]:
test3 = ["Congratulations you won lottery"]

test3_vec = tfidf.transform(test3)

prediction = nb.predict(test3_vec)

if prediction[0] == 1:
    print("SPAM")
else:
    print("HAM")

SPAM

##Conclusion:
####In this task, I built a Spam SMS classifier using Machine Learning. I cleaned the data and converted text into numerical form using TF-IDF vectorization. Three machine learning models were trained and compared:

1. Logistic Regression
2. Naive Bayes
3. Support Vector Machine (SVM)

##Result:
####The Naive Bayes model achieved the highest accuracy of 97.48%. Therefore, this model was selected as the final model. It was able to correctly classify messages as spam or ham, helping to filter unwanted SMS messages effectively.